language: python
python:
  - "3.6-dev" # 3.6 development branch
# command to install dependencies

install:
  - pip install -r requirements.txt
  - npm install
  - npm install -g jshint
# command to run tests
script:
#  - pytest # or py.test for Python versions 3.5 and below
  - flake8 --exclude=./*venv
  - npm test
